name: Deploy Angular App to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Angular app
      run: npm run build --prod
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        
    - name: Deploy to Azure Static Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        app_location: '/' # The location of the Angular app within the artifact
        app_artifact_location: 'dist' # The path of the Angular app artifact
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}